const ActionTypes = [
  // Authentication
  'AUTH_LOAD_REQUEST',
  'AUTH_LOAD_SUCCESS',
  'AUTH_LOAD_FAILURE',

  'AUTH_LOGIN_REQUEST',
  'AUTH_LOGIN_SUCCESS',
  'AUTH_LOGIN_FAILURE',

  'AUTH_LOGOUT_REQUEST',
  'AUTH_LOGOUT_SUCCESS',
  'AUTH_LOGOUT_FAILURE',

  'AUTH_RESET_REQUEST',
  'AUTH_RESET_SUCCESS',
  'AUTH_RESET_FAILURE',

  // Account
  'ACCOUNT_UPDATE_REQUEST',
  'ACCOUNT_UPDATE_SUCCESS',
  'ACCOUNT_UPDATE_FAILURE',
  'ACCOUNT_CHANGEPW_REQUEST',
  'ACCOUNT_CHANGEPW_SUCCESS',
  'ACCOUNT_CHANGEPW_FAILURE',
  'ACCOUNT_DELETE_REQUEST',
  'ACCOUNT_DELETE_SUCCESS',
  'ACCOUNT_DELETE_FAILURE',
  'ACCOUNT_VERIFY_REQUEST',
  'ACCOUNT_VERIFY_SUCCESS',
  'ACCOUNT_VERIFY_FAILURE',

  // Modal
  'MODAL_RECEIVED',
  'MODAL_DISMISS',

  // Notification
  'NOTIFICATION_RECEIVED',
  'NOTIFICATION_DISMISS',


  // Invites
  'INVITE_REQUEST',
  'INVITE_SUCCESS',
  'INVITE_FAILURE',


  // test
  'TEST_SUCCESS',
];

export default ActionTypes.reduce((prev, cur) => {
  const next = prev;
  next[cur] = cur;
  return next;
}, {});
